# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getCallPrice <- function(Expiry = 0.5, Strike = 100, Spot = 120, Vol = 0.2, r = 0.06, NumberOfPaths = 10000L) {
    .Call(`_optionPricer1_getCallPrice`, Expiry, Strike, Spot, Vol, r, NumberOfPaths)
}

rcpp_hello_world <- function() {
    .Call(`_optionPricer1_rcpp_hello_world`)
}

